# Generated by Django 2.0.6 on 2018-10-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('image_classification', models.CharField(blank=True, choices=[('ASSESSED', 'assessed FFPA'), ('PARTIAL', 'partial FFPA'), ('NOT_ASSESSED', 'not assessed FFPA'), ('UNKNOWN', 'unknown')], max_length=12)),
                ('updated_by_user', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
