# Generated by Django 2.0.6 on 2018-10-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image',
            field=models.ImageField(upload_to='pics_to_classify/'),
        ),
    ]
