# Generated by Django 2.1.2 on 2019-04-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_auto_20181016_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='model_type',
            field=models.CharField(blank=True, choices=[('WESTSIDE', 'westside model'), ('EASTSIDE', 'eastside model')], max_length=8),
        ),
        migrations.AlterField(
            model_name='img',
            name='image_classification',
            field=models.CharField(blank=True, choices=[('ASSESSED', 'assessed FFPA'), ('NOT_ASSESSED', 'not assessed FFPA'), ('REVIEW_NEEDED', 'review needed')], max_length=12),
        ),
    ]
