# Generated by Django 2.1.2 on 2019-04-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_auto_20190429_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='image_classification',
            field=models.CharField(blank=True, choices=[('ASSESSED', 'assessed FFPA'), ('NOT_ASSESSED', 'not assessed FFPA'), ('REVIEW_NEEDED', 'review needed')], max_length=13),
        ),
    ]
